dist: xenial
language: python
python:
        - "3.8"
        - "3.7"
        - "3.6"
addons:
        apt:
                packages:
                        - "python3"
                        - "python3-pip"
before_install:
        - pip3 install -r requirements.txt
script:
        - python3 corrnet.py -cm ./data/random_correlation.tsv -pm ./data/random_p_value.tsv --prefix firstproject
notification:
        email: false
